name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI_BAR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    steps:
      - name: Download artifact from CI
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Authenticate with GitHub Package Registry
      - name: Authenticate with GPR
        run: echo "//mvn.pkg.github.com/${{ github.repository.owner }}/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.m2/settings.xml

      # Download the artifact from GitHub Package Registry
      - name: Download artifact
        run: mvn -q dependency:get -Dartifact=${{ github.event.workflow_run.head_repository.owner }}:${{ github.event.workflow_run.head_repository.name }}:${{ github.event.workflow_run.head_commit.message }}
        
      # Add deployment steps using the downloaded artifact
